import type { Project } from "./types";

export const PROJECTS: Project[] = [
  { name: "CYCLE", slug: "cycle", tagline: "Cyberpunk HIIT workout timer & music PWA", date: "2026-06-21",
    cats: ["Web App"], vis: "Public", icon: "⏱️",
    desc: "A futuristic, installable PWA for high-intensity workouts. Precision interval timer with 12 built-in plans plus a custom plan builder (26 segment types), smart repetition, pro boxing-gym sounds, and a 180+ track curated YouTube music library with live search. Offline-first.",
    tech: ["Vite","Vanilla JS","Tailwind v4","Netlify Functions","Web Audio API","PWA"],
    live: "https://workouttimerpro.netlify.app", github: "https://github.com/blakazulu/Workout-Timer" },

  { name: "New Home Owner", slug: "new-home-owner", tagline: "Organize your apartment purchase, end to end", date: "2026-06-19",
    cats: ["AI","Web App"], vis: "Private", icon: "🏠",
    desc: `Hebrew RTL platform (“הדירה שלי”) that helps Israeli apartment buyers run the whole purchase from one place: AI auto-classifies contracts, payment confirmations and mortgage documents, a dashboard tracks payments on a timeline from lottery draw to key handover, an AI assistant answers purchase questions, and floor plans turn into 3D renders. Google Cloud, passwordless Google sign-in, encrypted. In beta.`,
    tech: ["TypeScript","Google Cloud","AI","Google Auth","RTL"],
    live: "https://new-home-owner.online" },

  { name: "AIEMD Platform", slug: "aiemd-platform", tagline: "AI-enhanced medical decisions", date: "2026-06-13",
    cats: ["AI","Web App"], vis: "Private", icon: "🏥",
    desc: "AIEMD.ai — an Angular platform that brings AI into clinical decision-making to support healthcare professionals. Private build.",
    tech: ["Angular","TypeScript","AI"],
    live: "https://aiemdplatform.netlify.app" },

  { name: "ChatHop", slug: "chathop", tagline: "WhatsApp anyone without saving the number", date: "2026-06-09",
    cats: ["Web App"], vis: "Private", icon: "💬",
    desc: "A tiny utility that opens a WhatsApp chat with any phone number directly — no need to add the contact to your phone first. Type the number, hop straight into the conversation.",
    tech: ["HTML","JavaScript"],
    live: "https://chathop.netlify.app" },

  { name: "חשבונייה (Math Practice)", slug: "math-practice", tagline: "Advanced 6th-grade math prep (Hebrew)", date: "2026-05-18",
    cats: ["Education","Web App"], vis: "Public", icon: "➗",
    desc: "Hebrew RTL math-practice app prepping 6th graders for the gifted-math entrance exam. 497 original questions across 23 topics, 7 full mock exams, graduated hints, 60-minute timed tests, a personal mistake-review queue, and multi-user local profiles. Free, device-only storage.",
    tech: ["TypeScript","RTL","Local-first"],
    live: "https://adv-math-practice.netlify.app", github: "https://github.com/blakazulu/math-practice" },

  { name: "Az Ma Kore", slug: "az-ma-kore", tagline: "Make sense of the sirens", date: "2026-04-06",
    cats: ["Web App"], vis: "Private", icon: "🚨",
    desc: `Hebrew RTL dashboard (“אז מה קורה”) that analyses Israel's Home Front Command (Pikud HaOref) alert data and visualises patterns by city — response times, quiet windows and real-time alert info — to help people understand what's happening around them. Analysis only, not a substitute for official guidance.`,
    tech: ["JavaScript","Pikud HaOref data","RTL"],
    live: "https://az-ma-kore.netlify.app" },

  { name: "Lumi Kid", slug: "lumi-kid", tagline: "AI English tutor for kids", date: "2026-03-16",
    cats: ["Education","AI","Web App"], vis: "Private", icon: "🎓",
    desc: `“Lumi” — an AI-powered English-learning app for children in grades 3–7, with personalised practice and prep for Meitzav, Israel’s standardised English assessment. Hebrew RTL interface.`,
    tech: ["TypeScript","AI","RTL"],
    live: "https://lumi-kid.netlify.app" },

  { name: "Past Palette", slug: "past-palette", tagline: "Color the ancient world with AI", date: "2026-02-07",
    cats: ["AI","Web App"], vis: "Public", icon: "🎨",
    desc: "Reconstructs the original colors of archaeological artifacts. Photograph an artifact, pick a culture (Egyptian, Roman, Greek, Mesopotamian) and Google Gemini generates a historically-grounded colorized version with a before/after slider. English + Hebrew.",
    tech: ["TypeScript","Google Gemini","RTL"],
    live: "https://past-palette.netlify.app", github: "https://github.com/blakazulu/past-palette" },

  { name: "Save The Past", slug: "save-the-past", tagline: "AI 3D reconstruction of artifacts", date: "2026-02-04",
    cats: ["AI","Web App"], vis: "Public", icon: "🏺",
    desc: "Turns multi-angle phone photos of an artifact into an interactive 3D model, plus AI analysis of material, estimated age and cultural context. Works offline at remote dig sites, mobile-first, installable. English + Hebrew, all data on-device.",
    tech: ["TypeScript","AI 3D","PWA","Offline-first"],
    live: "https://save-the-past.netlify.app", github: "https://github.com/blakazulu/save-the-past" },

  { name: "STEM Explorers", slug: "stem-explorers", tagline: "STEM learning platform for schools", date: "2026-01-22",
    cats: ["Education","AI","Web App"], vis: "Public", icon: "🔬",
    desc: "Role-based learning platform (admin / teacher / parent / student) for elementary STEM education. Pedagogical model tree, student research journals, AI-generated reports, teacher forum + chatbot, and documentation galleries — each role gets a distinct themed UI. RTL Hebrew, installable.",
    tech: ["Next.js 16","TypeScript","Firebase","Tailwind","Gemini","Botpress"],
    live: "https://stem-explorers.netlify.app", github: "https://github.com/blakazulu/stem-explorers" },

  { name: "ArcheoTriage", slug: "archeotriage", tagline: "First aid for archaeologists", date: "2026-01-12",
    cats: ["AI","Web App"], vis: "Public", icon: "🩺",
    desc: "Mobile-first field app that helps archaeologists protect artifacts at the moment of discovery: quick-reference preservation guides by material, color-coded environmental risk warnings, AI photo identification, and field documentation. Hebrew + English, RTL.",
    tech: ["TypeScript","AI Identification","Mobile-first"],
    live: "https://archeotriage.netlify.app", github: "https://github.com/blakazulu/ArcheoTriage" },

  { name: "KeyQuest", slug: "keyquest", tagline: "Learn touch typing, game-style", date: "2026-01-09",
    cats: ["Education","Web App"], vis: "Public", icon: "⌨️",
    desc: "A game-driven typing tutor that takes you from the home row to fluency. Structured learning path, real-time WPM & accuracy tracking, on-screen keyboard with finger guides, bite-size sessions, and WCAG 2.2 accessibility. Built for all ages.",
    tech: ["Next.js","TypeScript","WCAG 2.2"],
    live: "https://keyquest-app.netlify.app", github: "https://github.com/blakazulu/KeyQuest" },

  { name: "FloatJet", slug: "floatjet", tagline: "Honest tools & gear for remote workers", date: "2025-12-21",
    cats: ["Content","Web App"], vis: "Public", icon: "🛫",
    desc: "A no-nonsense review site for remote-work tools, gear and guides — VPNs, project management, monitors, chairs, home-office setups — all personally tested. Fast static site with instant full-text search.",
    tech: ["Astro 5","MDX","Tailwind 4","Pagefind","Partytown"],
    live: "https://floatjet.com", github: "https://github.com/blakazulu/floatjet" },

  { name: "AI Image Generator", slug: "ai-image-generator", tagline: "Free AI image generation inside Claude (MCP)", date: "2025-12-20",
    cats: ["Dev Tool","AI"], vis: "Public", icon: "🖼️",
    desc: "An MCP server that adds free AI image generation to Claude, Cursor and VS Code via HuggingFace (Stable Diffusion XL / FLUX). Natural-language prompts, specialized logo & UI/UX models, and a one-line install. Published on npm as mcp-hf-images.",
    tech: ["Node.js","MCP SDK","HuggingFace","Stable Diffusion / FLUX"],
    live: "https://image-generator-mcp.netlify.app", github: "https://github.com/blakazulu/mcp-image-server",
    npm: "https://www.npmjs.com/package/mcp-hf-images" },

  { name: "Hotjar Blocker", slug: "hotjar-blocker", tagline: "Block Hotjar tracking on any site", date: "2025-11-09",
    cats: ["Extension"], vis: "Public", icon: "🛡️",
    desc: "Chrome & Firefox extensions that block all Hotjar tracking, session recordings and heatmaps on the domains you choose. One-click 'add current domain', real-time block counter, on-page notifications and a synced domain list. Privacy-first, fully local.",
    tech: ["Chrome MV3","Firefox WebExtension","declarativeNetRequest"],
    live: "https://hotjarblocker.netlify.app", github: "https://github.com/blakazulu/hotjar-extensions" },

  { name: "MortgageFix (משכנתFix)", slug: "mortgagefix", tagline: "Guidance through the mortgage maze", date: "2025-07-08",
    cats: ["Web App"], vis: "Standalone", icon: "🏦",
    desc: "Hebrew RTL site for a mortgage guidance and consultation service (משכנתFix), helping people compare options and make mortgage decisions. Built and deployed from Bolt — no linked Git repo.",
    tech: ["Bolt","Static","RTL"],
    live: "https://gregarious-kashata-cbfd50.netlify.app" },

  { name: "Kiryat Begin — Desert Science", slug: "kiryat-begin-desert-science", tagline: "Desert science, in Hebrew", date: "2025-05-11",
    cats: ["Education","Web App"], vis: "Standalone", icon: "🏜️",
    desc: `A Hebrew RTL site for “קריית בגין למדע מדברי” (Kiryat Begin for Desert Science) — science education themed around the desert. Published via Netlify Drop, no linked Git repo.`,
    tech: ["Static","RTL"],
    live: "https://desert-tech-begin.netlify.app" },

  { name: "Search MCP", slug: "search-mcp", tagline: "Local semantic code search for your AI (MCP)", date: null,
    cats: ["Dev Tool"], vis: "Public", icon: "🔍",
    desc: "An MCP server that gives your AI assistant semantic search over your whole codebase — 58× fewer tokens than grep, ~400 ms search, 100% local, no API keys. Works with Claude Desktop/Code, Cursor and Windsurf, with a standalone CLI too.",
    tech: ["TypeScript","MCP SDK","LanceDB","BGE Embeddings","DirectML GPU"],
    github: "https://github.com/blakazulu/search-mcp",
    npm: "https://www.npmjs.com/package/@liraz-sbz/search-mcp" },

  { name: "ScalpelPDF", slug: "scalpelpdf", tagline: "Privacy-first PDF editor for Windows", date: null,
    cats: ["Dev Tool"], vis: "Fork", icon: "📄",
    desc: "A Windows PDF editor you can install or run portable — no account, no subscription, no telemetry. GPLv3 open source. (Fork of KillerPDF.)",
    tech: ["C#",".NET","GPLv3"],
    github: "https://github.com/blakazulu/ScalpelPDF" },
];
